version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: movieuser
      POSTGRES_PASSWORD: moviepass
      POSTGRES_DB: moviedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://movieuser:moviepass@db:5432/moviedb
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/').getcode()==200 else 1)\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build: ./nginx
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped

volumes:
  pgdata:
